[package]
name = "asmbl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0.22"
rand = "0.8.4"
rlua = "0.19.4"
strum = "0.24.1"
strum_macros = "0.24.3"
